version: '3.4'

services: 
    nginx:
        build: 
            context: ./Nginx
            dockerfile: Dockerfile
        ports: 
            - 8055:80
        restart: always
    client:
        build:
            context: ./src/WebApp/ClientApp
            dockerfile: Dockerfile
        ports: 
            - 5000:80
    dncapi:
        build: 
            context: ./src/WebApp
            dockerfile: Dockerfile
        ports: 
            - 3000:80